import { useCallback, useEffect, useRef, useState } from "react";
import { Check, ChevronLeft, Clipboard, Eye, EyeOff, Film, FolderOpen, Image as ImageIcon, Info, Layers3, Pause, Play, Plus, Save, Scissors, Share2, SlidersHorizontal, Sparkles, Type, Volume2, X } from "lucide-react";
import { api } from "../../lib/api";
import { formatTime } from "../../lib/format";
import type { Asset, CandidateClip, EditDecisionList, Overlay, Project } from "../../lib/types";
import { useAppStore } from "../../state/useAppStore";

type Range = { start: number; end: number };
type VisualLayer = Extract<Overlay, { type: "video" | "image" }>;
type TextLayer = Extract<Overlay, { type: "text" }>;

export function ClipEditor({ clip, project, presetId, onClose }: { clip: CandidateClip; project: Project; presetId: string; onClose: () => void }) {
  const { data, addAsset: storeAsset, notify, setBusy } = useAppStore();
  const [edit, setEdit] = useState<EditDecisionList>(() => freshEdit(clip));
  const [tab, setTab] = useState<"info" | "crop" | "text" | "assets" | "shortcuts">("info");
  const [clipName, setClipName] = useState(clip.name ?? "");
  const [savedAt, setSavedAt] = useState<Date>();
  const [rendering, setRendering] = useState(false);
  const [output, setOutput] = useState<string>();
  const [playhead, setPlayhead] = useState(clip.startSeconds);
  const [playing, setPlaying] = useState(false);
  const [selection, setSelection] = useState<Range>({ start: clip.startSeconds, end: Math.min(clip.startSeconds + 1, clip.endSeconds) });
  const [selectedOverlay, setSelectedOverlay] = useState<string>();
  const [timelineMenu, setTimelineMenu] = useState<{ x: number; y: number }>();
  const [timelineHeight, setTimelineHeight] = useState(210);
  const [inspectorWidth, setInspectorWidth] = useState(300);
  const [timelineZoom, setTimelineZoom] = useState(1);
  const [cutOverlay, setCutOverlay] = useState<string>();
  const revisionRef = useRef(1);
  const foregroundVideoRef = useRef<HTMLVideoElement>(null);
  const backgroundVideoRef = useRef<HTMLVideoElement>(null);
  const timelineMenuRef = useRef<HTMLDivElement>(null);
  const timelineResizeRef = useRef<number | undefined>(undefined);
  const inspectorResizeRef = useRef<number | undefined>(undefined);
  const historyRef = useRef<EditDecisionList[]>([]);
  const redoRef = useRef<EditDecisionList[]>([]);
  const clipboardRef = useRef<{ overlay?: Overlay; segment?: Range } | undefined>(undefined);
  const fileUrl = api.fileUrl(project.source.path);
  const clipDuration = Math.max(.1, edit.trimEnd - edit.trimStart);
  const selectedLayer = edit.overlays.find(item => item.id === selectedOverlay);
  const selectedText = selectedLayer?.type === "text" ? selectedLayer : undefined;
  const visualLayers = edit.overlays.filter((item): item is VisualLayer => item.type === "video" || item.type === "image");
  const textLayers = edit.overlays.filter((item): item is TextLayer => item.type === "text");
  const audioLayers = edit.overlays.filter((item): item is Extract<Overlay, { type: "audio" }> => item.type === "audio");
  const visibility = { video: true, overlays: true, text: true, audio: true, ...edit.trackVisibility };

  useEffect(() => { api.loadEdit(clip.id).then(value => { if (value) { const normalized = { ...value, cutPoints: value.cutPoints ?? [], trackVisibility: { video: true, overlays: true, text: true, audio: true, ...value.trackVisibility } }; setEdit(normalized); setPlayhead(normalized.trimStart); setSelection({ start: normalized.trimStart, end: Math.min(normalized.trimStart + 1, normalized.trimEnd) }); } }); }, [clip.id]);
  const saveEdit = useCallback(async () => { await api.saveEdit({ ...edit, revision: ++revisionRef.current, cutPoints: edit.cutPoints ?? [] }); setSavedAt(new Date()); }, [edit]);
  useEffect(() => { const saveBeforeUpdate = (event: Event) => { const detail = (event as CustomEvent<{ tasks: Promise<unknown>[] }>).detail; if (detail?.tasks) detail.tasks.push(saveEdit()); }; window.addEventListener("banshee-before-update", saveBeforeUpdate); return () => window.removeEventListener("banshee-before-update", saveBeforeUpdate); }, [saveEdit]);
  useEffect(() => { const timer = window.setTimeout(() => saveEdit().catch(() => undefined), 700); return () => window.clearTimeout(timer); }, [saveEdit]);
  useEffect(() => { if (!clipName.trim() || clipName.trim() === clip.name) return; const timer = window.setTimeout(() => api.renameCandidate(clip.id, clipName.trim()).then(() => setSavedAt(new Date())).catch(error => notify(String(error))), 700); return () => window.clearTimeout(timer); }, [clip.id, clip.name, clipName, notify]);
  useEffect(() => { if (!timelineMenu) return; const close = (event: PointerEvent) => { if (!timelineMenuRef.current?.contains(event.target as Node)) setTimelineMenu(undefined); }; window.addEventListener("pointerdown", close); return () => window.removeEventListener("pointerdown", close); }, [timelineMenu]);
  useEffect(() => { if (!timelineMenu) return; const next = { x: Math.max(8, Math.min(timelineMenu.x, window.innerWidth - 220)), y: timelineMenu.y > window.innerHeight - 270 ? Math.max(8, timelineMenu.y - 260) : timelineMenu.y }; if (next.x !== timelineMenu.x || next.y !== timelineMenu.y) setTimelineMenu(next); }, [timelineMenu]);
  useEffect(() => { const menu = (event: Event) => { const detail = (event as CustomEvent<{ x: number; y: number }>).detail; if (detail) setTimelineMenu(detail); }; window.addEventListener("banshee-timeline-context", menu); return () => window.removeEventListener("banshee-timeline-context", menu); }, []);
  useEffect(() => { const zoom = (event: WheelEvent) => { if (!event.ctrlKey || !(event.target as Element).closest(".timeline")) return; event.preventDefault(); setTimelineZoom(current => Math.max(.6, Math.min(3, current + (event.deltaY < 0 ? .15 : -.15)))); }; window.addEventListener("wheel", zoom, { passive: false }); return () => window.removeEventListener("wheel", zoom); }, []);
  useEffect(() => { document.documentElement.style.setProperty("--timeline-zoom", String(timelineZoom)); }, [timelineZoom]);

  const update = <K extends keyof EditDecisionList>(key: K, value: EditDecisionList[K]) => { historyRef.current = [...historyRef.current.slice(-99), structuredClone(edit)]; redoRef.current = []; setEdit(current => ({ ...current, [key]: value })); };
  const updateCrop = (patch: Partial<EditDecisionList["crop"]>) => update("crop", { ...edit.crop, ...patch });
  const updateOverlay = (id: string, patch: Partial<Overlay>) => update("overlays", edit.overlays.map(item => item.id === id ? { ...item, ...patch } as Overlay : item));
  const seek = useCallback((time: number) => { const next = Math.max(edit.trimStart, Math.min(time, edit.trimEnd)); setPlayhead(next); for (const video of [foregroundVideoRef.current, backgroundVideoRef.current]) if (video && Math.abs(video.currentTime - next) > .04) video.currentTime = next; }, [edit.trimEnd, edit.trimStart]);
  function isRemoved(time: number) { return edit.removedRanges.find(range => time >= range.start && time < range.end); }
  function togglePlayback() { const video = foregroundVideoRef.current; if (!video) return; if (video.paused) { seek(playhead >= edit.trimEnd ? edit.trimStart : playhead); void video.play(); } else video.pause(); }
  function handleTimeUpdate() { const video = foregroundVideoRef.current; if (!video) return; const removed = isRemoved(video.currentTime); if (removed) { seek(removed.end); return; } if (video.currentTime >= edit.trimEnd) { video.pause(); seek(edit.trimEnd); return; } setPlayhead(video.currentTime); const background = backgroundVideoRef.current; if (background && Math.abs(background.currentTime - video.currentTime) > .08) background.currentTime = video.currentTime; }
  function segmentAt(time: number): Range { const bounds = [edit.trimStart, ...(edit.cutPoints ?? []).filter(point => point > edit.trimStart && point < edit.trimEnd), edit.trimEnd].sort((a, b) => a - b); const safeTime = Math.min(time, edit.trimEnd - .0001); const index = Math.max(0, bounds.slice(0, -1).findIndex((point, position) => safeTime >= point && safeTime < bounds[position + 1])); return { start: bounds[index], end: bounds[Math.min(index + 1, bounds.length - 1)] }; }
  function deleteSelection() { const start = Math.max(edit.trimStart, selection.start); const end = Math.min(edit.trimEnd, selection.end); if (end - start < .1) return; update("removedRanges", [...edit.removedRanges.filter(range => range.start !== start || range.end !== end), { start, end }].sort((a, b) => a.start - b.start)); seek(end); }
  function deleteSelected() { if (selectedOverlay) { update("overlays", edit.overlays.filter(item => item.id !== selectedOverlay)); setSelectedOverlay(undefined); } else deleteSelection(); }
  function undo() { const previous = historyRef.current.pop(); if (!previous) return; redoRef.current = [...redoRef.current.slice(-99), structuredClone(edit)]; setEdit(previous); setSelection(segmentAt(playhead)); }
  function redo() { const next = redoRef.current.pop(); if (!next) return; historyRef.current = [...historyRef.current.slice(-99), structuredClone(edit)]; setEdit(next); setSelection(segmentAt(playhead)); }
  function copySelected() { if (selectedOverlay) clipboardRef.current = { overlay: structuredClone(edit.overlays.find(item => item.id === selectedOverlay)) }; else clipboardRef.current = { segment: { ...selection } }; notify("Скопійовано"); }
  function cutSelected() { copySelected(); if (selectedOverlay) { setCutOverlay(selectedOverlay); update("overlays", edit.overlays.filter(item => item.id !== selectedOverlay)); setSelectedOverlay(undefined); } else deleteSelection(); }
  async function pasteSelected() { const copied = clipboardRef.current; if (!copied) return; if (copied.overlay) { const source = copied.overlay; const length = source.end - source.start; const start = Math.max(0, playhead - edit.trimStart); const layer = { ...source, id: crypto.randomUUID(), start, end: Math.min(clipDuration, start + length) } as Overlay; update("overlays", [...edit.overlays, layer]); setSelectedOverlay(layer.id); setCutOverlay(undefined); notify("Вставлено"); return; } if (copied.segment) { try { let asset = data?.assets.find(item => item.path === project.source.path); if (!asset) { asset = await api.importAsset(project.source.path); storeAsset(asset); } const length = copied.segment.end - copied.segment.start; const start = Math.max(0, playhead - edit.trimStart); const layer: VisualLayer = { type: "video", id: crypto.randomUUID(), assetId: asset.id, sourceOffset: copied.segment.start, start, end: Math.min(clipDuration, start + length), x: .5, y: .5, scale: 1 }; update("overlays", [...edit.overlays, layer]); setSelectedOverlay(layer.id); setCutOverlay(undefined); notify("Фрагмент вставлено"); } catch (error) { notify(String(error)); } } }
  function trimToPlayhead(keep: "left" | "right") { if (keep === "left" && playhead > edit.trimStart + .1) update("trimEnd", playhead); if (keep === "right" && playhead < edit.trimEnd - .1) update("trimStart", playhead); }
  function splitAtPlayhead() { if (playhead <= edit.trimStart + .05 || playhead >= edit.trimEnd - .05) { notify("Курсор має бути всередині кліпу"); return; } const points = edit.cutPoints ?? []; if (!points.some(point => Math.abs(point - playhead) < .05)) { update("cutPoints", [...points, playhead].sort((a, b) => a - b)); setSelection({ start: Math.max(edit.trimStart, ...points.filter(point => point < playhead)), end: playhead }); } }
  function addText() { const layer: TextLayer = { type: "text", id: crypto.randomUUID(), text: "Ваш текст", color: "#ffffff", size: 56, x: .5, y: .16, start: Math.max(0, playhead - edit.trimStart), end: Math.min(clipDuration, Math.max(0, playhead - edit.trimStart) + 5), fontFamily: "Arial", underline: false, background: false, backgroundColor: "#000000", backgroundRadius: 8, lane: textLayers.length }; update("overlays", [...edit.overlays, layer]); setSelectedOverlay(layer.id); }
  function addResource(asset: Asset, startAt = Math.max(0, playhead - edit.trimStart)) { const start = Math.max(0, Math.min(startAt, clipDuration - .15)); const layer: Overlay = asset.kind === "audio" ? { type: "audio", id: crypto.randomUUID(), assetId: asset.id, start, end: clipDuration, volume: .7 } : asset.kind === "image" ? { type: "image", id: crypto.randomUUID(), assetId: asset.id, start, end: Math.min(clipDuration, start + 5), x: .5, y: .5, scale: .45 } : { type: "video", id: crypto.randomUUID(), assetId: asset.id, start, end: Math.min(clipDuration, start + 8), x: .5, y: .5, scale: .45, chromaKey: { color: "#00ff00", similarity: .18, blend: .08, spill: .15 } }; update("overlays", [...edit.overlays, layer]); setSelectedOverlay(layer.id); }
  async function importAndAdd() { try { const path = await api.chooseAsset(); if (!path) return; const asset = await api.importAsset(path); storeAsset(asset); addResource(asset); } catch (error) { notify(String(error)); } }
  async function render() { setRendering(true); setBusy(true); try { await saveEdit(); const job = await api.render(project.id, clip.id, presetId); setOutput(job.outputPath); notify(job.warning ?? "Відео успішно відрендерено"); } catch (error) { if (!String(error).includes("RENDER_CANCELLED")) notify(String(error)); } finally { setRendering(false); setBusy(false); } }
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if ((event.target as HTMLElement).matches("input, textarea, select")) return; const modifier = event.ctrlKey || event.metaKey; if (event.code === "Space") { event.preventDefault(); togglePlayback(); } if (modifier && event.code === "KeyS") { event.preventDefault(); void saveEdit(); } if (modifier && event.code === "KeyB") { event.preventDefault(); splitAtPlayhead(); } if (modifier && event.code === "KeyZ") { event.preventDefault(); event.shiftKey ? redo() : undo(); } if (modifier && event.code === "KeyC") { event.preventDefault(); copySelected(); } if (modifier && event.code === "KeyX") { event.preventDefault(); cutSelected(); } if (modifier && event.code === "KeyV") { event.preventDefault(); void pasteSelected(); } if (event.code === "ArrowLeft" || event.code === "ArrowRight") { event.preventDefault(); seek(playhead + (event.code === "ArrowLeft" ? -5 : 5)); } if (event.key === "Delete" || event.key === "Backspace") { event.preventDefault(); deleteSelected(); } }; window.addEventListener("keydown", onKeyDown, true); return () => window.removeEventListener("keydown", onKeyDown, true); });

  return <div className="editor-backdrop"><section className="editor-shell"><header className="editor-header"><div><button className="icon-button" onClick={onClose}><ChevronLeft size={20}/></button><div><span className="eyebrow">Редактор кліпу</span><strong>{clipName || project.name}</strong></div></div><div className="save-state">{savedAt ? <><Check size={14}/>Збережено</> : "Autosave увімкнено"}</div><div><button className="secondary" onClick={() => saveEdit()}><Save size={16}/>Зберегти</button><button className="primary" onClick={render} disabled={rendering}><Sparkles size={17}/>{rendering ? "Рендер…" : "Експортувати"}</button><button className="icon-button" onClick={onClose}><X size={19}/></button></div></header>
    <div className="editor-main" style={{ gridTemplateColumns: `74px minmax(420px,1fr) ${inspectorWidth}px` }}><aside className="editor-tools"><button className={tab === "info" ? "active" : ""} onClick={() => setTab("info")}><Info size={18}/>Info</button><button className={tab === "crop" ? "active" : ""} onClick={() => setTab("crop")}><SlidersHorizontal size={18}/>Кадр</button><button className={tab === "text" ? "active" : ""} onClick={() => setTab("text")}><Type size={18}/>Текст</button><button className={tab === "assets" ? "active" : ""} onClick={() => setTab("assets")}><Layers3 size={18}/>Ресурси</button><button className={tab === "shortcuts" ? "active" : ""} onClick={() => setTab("shortcuts")}><Clipboard size={18}/>Клавіші</button></aside>
      <div className="preview-stage"><div className={`phone-preview mode-${edit.crop.mode}`} style={{ "--zoom": edit.crop.zoom } as React.CSSProperties}>{fileUrl ? <>{edit.crop.mode === "blurredBackground" && <video ref={backgroundVideoRef} className="blur-background-video" src={fileUrl} muted playsInline aria-hidden="true" style={{ visibility: visibility.video ? "visible" : "hidden" }}/>}<video ref={foregroundVideoRef} className="editor-preview-video" src={fileUrl} muted={!visibility.audio} playsInline style={{ visibility: visibility.video ? "visible" : "hidden" }} onLoadedMetadata={() => seek(edit.trimStart)} onPlay={() => { setPlaying(true); const background = backgroundVideoRef.current; if (background) void background.play(); }} onPause={() => { setPlaying(false); backgroundVideoRef.current?.pause(); }} onTimeUpdate={handleTimeUpdate}/></> : <div className="video-placeholder"><Film size={42}/></div>}
        {visibility.overlays && visualLayers.map(layer => <PreviewLayer key={layer.id} layer={layer} asset={data?.assets.find(item => item.id === layer.assetId)} currentTime={playhead - edit.trimStart} selected={layer.id === selectedOverlay} onSelect={() => setSelectedOverlay(layer.id)} onChange={patch => updateOverlay(layer.id, patch)}/>)}
        {visibility.text && textLayers.map(layer => <TextPreview key={layer.id} layer={layer} currentTime={playhead - edit.trimStart} selected={layer.id === selectedOverlay} onSelect={() => setSelectedOverlay(layer.id)} onChange={patch => updateOverlay(layer.id, patch)}/>)}
        {visibility.audio && audioLayers.map(layer => <AudioPreview key={layer.id} layer={layer} asset={data?.assets.find(item => item.id === layer.assetId)} currentTime={playhead - edit.trimStart} playing={playing}/>)}<div className="safe-zone"/></div></div>
      <aside className="inspector"><div className="inspector-resize" onPointerDown={event => { inspectorResizeRef.current = event.clientX; event.currentTarget.setPointerCapture(event.pointerId); }} onPointerMove={event => { if (inspectorResizeRef.current === undefined) return; const delta = inspectorResizeRef.current - event.clientX; inspectorResizeRef.current = event.clientX; setInspectorWidth(current => Math.max(240, Math.min(520, current + delta))); }} onPointerUp={() => { inspectorResizeRef.current = undefined; }}/>{tab === "info" && <InfoPanel project={project} edit={edit} clipName={clipName} onName={setClipName} onFps={fps => update("fps", fps)}/>} {tab === "crop" && <CropPanel edit={edit} onChange={updateCrop}/>} {tab === "text" && <TextPanel selected={selectedText} textLayers={textLayers} onAdd={addText} onSelect={setSelectedOverlay} onChange={patch => selectedText && updateOverlay(selectedText.id, patch)} onDelete={() => selectedText && deleteSelected()}/>} {tab === "assets" && <AssetsPanel assets={data?.assets ?? []} overlays={edit.overlays} selected={selectedOverlay} visual={selectedLayer?.type === "video" || selectedLayer?.type === "image" ? selectedLayer : undefined} onSelect={setSelectedOverlay} onAdd={addResource} onImport={importAndAdd} onChange={patch => selectedLayer && updateOverlay(selectedLayer.id, patch)} onDelete={deleteSelected}/>} {tab === "shortcuts" && <ShortcutsPanel/>}</aside>
    </div>
    <footer className="timeline"><div className="timeline-toolbar"><button onClick={togglePlayback}>{playing ? <Pause fill="currentColor" size={14}/> : <Play fill="currentColor" size={14}/>}</button><span>{formatTime(playhead)} / {formatTime(edit.trimEnd)}</span><div className="timeline-spacer"/><span>Space: play · Ctrl+B: розрізати · ←/→: ±5 с · Del: видалити</span></div><TimelineTrack edit={edit} playhead={playhead} selection={selection} visible={visibility.video} onVisible={value => update("trackVisibility", { ...visibility, video: value })} onSeek={seek} onSelect={range => { setSelection(range); setSelectedOverlay(undefined); }} onContextMenu={setTimelineMenu}/><TimelineLayers label="OVERLAYS" layers={visualLayers} visible={visibility.overlays} onVisible={value => update("trackVisibility", { ...visibility, overlays: value })} duration={clipDuration} selected={selectedOverlay} onSelect={setSelectedOverlay} onChange={updateOverlay} onDropAsset={(assetId, start) => { const asset = data?.assets.find(item => item.id === assetId); if (asset) addResource(asset, start); }}/><TimelineLayers label="TEXT" layers={textLayers} visible={visibility.text} onVisible={value => update("trackVisibility", { ...visibility, text: value })} duration={clipDuration} selected={selectedOverlay} onSelect={setSelectedOverlay} onChange={updateOverlay}/><TimelineLayers label="AUDIO" layers={audioLayers} visible={visibility.audio} onVisible={value => update("trackVisibility", { ...visibility, audio: value })} duration={clipDuration} selected={selectedOverlay} onSelect={setSelectedOverlay} onChange={updateOverlay} onDropAsset={(assetId, start) => { const asset = data?.assets.find(item => item.id === assetId); if (asset) addResource(asset, start); }}/>
      {timelineMenu && <div className="timeline-context" ref={timelineMenuRef} style={{ left: timelineMenu.x, top: timelineMenu.y }}><button onClick={() => { splitAtPlayhead(); setTimelineMenu(undefined); }}><Scissors size={14}/>Розрізати в курсорі</button><button onClick={() => { copySelected(); setTimelineMenu(undefined); }}><Clipboard size={14}/>Копіювати</button><button onClick={() => { pasteSelected(); setTimelineMenu(undefined); }}><Clipboard size={14}/>Вставити</button><button onClick={() => { trimToPlayhead("left"); setTimelineMenu(undefined); }}>Обрізати справа</button><button onClick={() => { trimToPlayhead("right"); setTimelineMenu(undefined); }}>Обрізати зліва</button><button className="danger" onClick={() => { deleteSelection(); setTimelineMenu(undefined); }}>Видалити фрагмент</button></div>}</footer>
    {output && <div className="render-complete"><Check size={18}/><span>Файл готовий</span><button onClick={() => api.share(output).catch(error => notify(String(error)))}><Share2 size={16}/>Поділитися</button><button onClick={() => navigator.clipboard.writeText(output).then(() => notify("Шлях скопійовано"))}><Clipboard size={16}/>Копіювати шлях</button><button onClick={() => api.reveal(output)}><FolderOpen size={16}/>Показати</button></div>}
  </section></div>;
}

function InfoPanel({ project, edit, clipName, onName, onFps }: { project: Project; edit: EditDecisionList; clipName: string; onName: (name: string) => void; onFps: (fps: number) => void }) { const max = Math.max(24, Math.round(project.source.fps)); const values = [24, 25, 30, 50, 60, max].filter((value, index, list) => value <= max && list.indexOf(value) === index); return <><div className="inspector-title"><div><Info size={18}/>Інформація</div><span>autosave</span></div><Control label="Назва моменту"><input value={clipName} placeholder={project.name} onChange={event => onName(event.target.value)}/></Control><Control label="FPS експорту"><select value={edit.fps ?? max} onChange={event => onFps(+event.target.value)}>{values.map(value => <option key={value} value={value}>{value} FPS</option>)}</select></Control><div className="info-details"><span>Файл<strong>{project.source.fileName}</strong></span><span>Оригінал<strong>{project.source.width}×{project.source.height} · {project.source.fps.toFixed(1)} FPS</strong></span><span>Діапазон<strong>{formatTime(edit.trimStart)} — {formatTime(edit.trimEnd)}</strong></span></div></>; }
function CropPanel({ edit, onChange }: { edit: EditDecisionList; onChange: (patch: Partial<EditDecisionList["crop"]>) => void }) { return <><div className="inspector-title"><div><SlidersHorizontal size={18}/>Кадрування</div><span>9:16</span></div><Control label="Режим"><select value={edit.crop.mode} onChange={event => onChange({ mode: event.target.value as EditDecisionList["crop"]["mode"] })}><option value="center">По центру</option><option value="dynamic">Динамічний</option><option value="blurredBackground">Розмитий фон</option></select></Control><Control label={`Zoom · ${edit.crop.zoom.toFixed(2)}×`}><input type="range" min="1" max="3" step=".05" value={edit.crop.zoom} onChange={event => onChange({ zoom: +event.target.value })}/></Control></>; }
function TextPanel({ selected, textLayers, onAdd, onSelect, onChange, onDelete }: { selected?: TextLayer; textLayers: TextLayer[]; onAdd: () => void; onSelect: (id: string) => void; onChange: (patch: Partial<TextLayer>) => void; onDelete: () => void }) { const fonts = ["Arial", "Calibri", "Segoe UI", "Times New Roman", "Verdana", "Georgia", "Courier New"]; return <><div className="inspector-title"><div><Type size={18}/>Текст</div><button className="icon-button small" onClick={onAdd}><Plus size={15}/></button></div><button className="resource-add" onClick={onAdd}><Plus size={18}/><div><strong>Додати текст</strong><span>Новий шар поверх попередніх</span></div></button>{selected && <><Control label="Текст"><textarea value={selected.text} onChange={event => onChange({ text: event.target.value })}/></Control><Control label="Шрифт"><select value={selected.fontFamily ?? "Arial"} onChange={event => onChange({ fontFamily: event.target.value })}>{fonts.map(font => <option value={font} key={font}>{font}</option>)}</select></Control><Control label="Розмір"><input type="number" min="1" value={selected.size} onChange={event => onChange({ size: Math.max(1, +event.target.value) })}/></Control><div className="row-controls"><Control label="Колір"><input type="color" value={selected.color} onChange={event => onChange({ color: event.target.value })}/></Control><Control label="Підкреслення"><input type="checkbox" checked={selected.underline ?? false} onChange={event => onChange({ underline: event.target.checked })}/></Control></div><Control label="Підкладка"><label className="check-control"><input type="checkbox" checked={selected.background ?? false} onChange={event => onChange({ background: event.target.checked })}/>Показувати</label></Control>{selected.background && <><Control label="Колір підкладки"><input type="color" value={selected.backgroundColor ?? "#000000"} onChange={event => onChange({ backgroundColor: event.target.value })}/></Control><Control label={`Заокруглення · ${selected.backgroundRadius ?? 8}px`}><input type="range" min="0" max="40" value={selected.backgroundRadius ?? 8} onChange={event => onChange({ backgroundRadius: +event.target.value })}/></Control></>}<button className="danger-link" onClick={onDelete}>Видалити текст</button></>}<div className="layer-list">{textLayers.map(layer => <button className="layer-row" key={layer.id} onClick={() => onSelect(layer.id)}><Type size={16}/><span>{layer.text || "Текст"}</span></button>)}</div></>; }
function AssetsPanel({ assets, overlays, selected, visual, onSelect, onAdd, onImport, onChange, onDelete }: { assets: Asset[]; overlays: Overlay[]; selected?: string; visual?: VisualLayer; onSelect: (id: string) => void; onAdd: (asset: Asset) => void; onImport: () => void; onChange: (patch: Partial<Overlay>) => void; onDelete: () => void }) { const choose = (asset: Asset) => { const existing = overlays.find(layer => "assetId" in layer && layer.assetId === asset.id); if (existing) onSelect(existing.id); else onAdd(asset); }; return <><div className="inspector-title"><div><Layers3 size={18}/>Ресурси</div><button className="icon-button small" onClick={onImport} title="Імпортувати файл"><Plus size={15}/></button></div><p className="asset-panel-hint">Натисніть, щоб додати. Перетягніть на доріжку для точного часу.</p>{visual && <VisualControls layer={visual} onChange={onChange}/>}<div className="asset-library">{assets.map(asset => { const existing = overlays.find(layer => "assetId" in layer && layer.assetId === asset.id); return <button draggable key={asset.id} className={`layer-row ${existing ? "in-project" : ""}`} onClick={() => choose(asset)} onDragStart={event => { event.dataTransfer.effectAllowed = "copy"; event.dataTransfer.setData("application/x-banshee-asset", asset.id); }}>{asset.kind === "audio" ? <Volume2 size={17}/> : asset.kind === "image" ? <ImageIcon size={17}/> : <Film size={17}/>}<span>{asset.name}</span>{existing ? <Check size={15}/> : <Plus size={15}/>}</button>; })}{!assets.length && <p className="hint">Медіатека порожня. Натисніть +, щоб імпортувати файл.</p>}</div><div className="layer-list">{overlays.filter(layer => layer.type !== "text").map(layer => <button className={`layer-row ${layer.id === selected ? "selected" : ""}`} key={layer.id} onClick={() => onSelect(layer.id)}>{layer.type === "audio" ? <Volume2 size={17}/> : layer.type === "image" ? <ImageIcon size={17}/> : <Film size={17}/>}<span>{layer.type === "audio" ? "Аудіошар" : layer.type === "image" ? "Зображення" : "Відеовставка"}</span>{layer.id === selected && <X size={15} onClick={event => { event.stopPropagation(); onDelete(); }}/>}</button>)}</div></>; }

function TimelineTrack({ edit, playhead, selection, visible, onVisible, onSeek, onSelect, onContextMenu }: { edit: EditDecisionList; playhead: number; selection: Range; visible: boolean; onVisible: (value: boolean) => void; onSeek: (time: number) => void; onSelect: (range: Range) => void; onContextMenu: (position: { x: number; y: number }) => void }) { const ref = useRef<HTMLDivElement>(null); const duration = Math.max(.1, edit.trimEnd - edit.trimStart); const bounds = [edit.trimStart, ...(edit.cutPoints ?? []).filter(point => point > edit.trimStart && point < edit.trimEnd), edit.trimEnd].sort((a, b) => a - b); const segments = bounds.slice(0, -1).map((start, index) => ({ start, end: bounds[index + 1] })); const removed = (segment: Range) => edit.removedRanges.some(range => range.start <= segment.start + .01 && range.end >= segment.end - .01); const toTime = (x: number) => { const rect = ref.current!.getBoundingClientRect(); return edit.trimStart + Math.max(0, Math.min(1, (x - rect.left) / rect.width)) * duration; }; const segment = (time: number) => segments.find(item => Math.min(time, edit.trimEnd - .0001) >= item.start && Math.min(time, edit.trimEnd - .0001) < item.end) ?? segments[0]; const selectAt = (time: number) => { onSeek(time); onSelect(segment(time)); }; return <div className={`timeline-track ${visible ? "" : "track-disabled"}`}><div className="track-label"><button className="track-eye" onClick={() => onVisible(!visible)} title={visible ? "Сховати відео" : "Показати відео"}>{visible ? <Eye size={15}/> : <EyeOff size={15}/>}</button><Film size={15}/>VIDEO</div><div ref={ref} className="timeline-canvas" onPointerDown={event => selectAt(toTime(event.clientX))} onContextMenu={event => { event.preventDefault(); selectAt(toTime(event.clientX)); onContextMenu({ x: event.clientX, y: event.clientY }); }}>{segments.filter(item => !removed(item)).map(item => <div className="track-clip source-fragment" key={`${item.start}-${item.end}`} style={{ left: `${(item.start - edit.trimStart) / duration * 100}%`, width: `${(item.end - item.start) / duration * 100}%` }}><span>Вихідне відео</span></div>)}{(edit.cutPoints ?? []).map(point => <div className="cut-marker" key={point} style={{ left: `${(point - edit.trimStart) / duration * 100}%` }}/>) }<div className="selection-block" style={{ left: `${(selection.start - edit.trimStart) / duration * 100}%`, width: `${(selection.end - selection.start) / duration * 100}%` }}/><div className="playhead" style={{ left: `${(playhead - edit.trimStart) / duration * 100}%` }}/></div></div>; }
function TimelineLayers({ label, layers, duration, visible, onVisible, selected, onSelect, onChange, onDropAsset }: { label: string; layers: Overlay[]; duration: number; visible: boolean; onVisible: (value: boolean) => void; selected?: string; onSelect: (id: string) => void; onChange: (id: string, patch: Partial<Overlay>) => void; onDropAsset?: (assetId: string, start: number) => void }) { const drag = useRef<{ id: string; kind: "move" | "resize"; x: number; start: number; end: number } | undefined>(undefined); const updateAt = (event: React.PointerEvent<HTMLButtonElement>) => { const current = drag.current; if (!current) return; const rect = event.currentTarget.parentElement!.getBoundingClientRect(); const delta = (event.clientX - current.x) / rect.width * duration; if (current.kind === "resize") onChange(current.id, { end: Math.max(current.start + .15, Math.min(duration, current.end + delta)) }); else { const length = current.end - current.start; const start = Math.max(0, Math.min(duration - length, current.start + delta)); onChange(current.id, { start, end: start + length }); } }; return <div className={`timeline-track ${visible ? "" : "track-disabled"}`}><div className="track-label"><button className="track-eye" onClick={() => onVisible(!visible)} title={visible ? "Вимкнути доріжку" : "Увімкнути доріжку"}>{visible ? <Eye size={15}/> : <EyeOff size={15}/>}</button>{label === "AUDIO" ? <Volume2 size={15}/> : label === "TEXT" ? <Type size={15}/> : <Layers3 size={15}/>} {label}</div><div className="timeline-canvas layer-canvas" onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); const assetId = event.dataTransfer.getData("application/x-banshee-asset"); const rect = event.currentTarget.getBoundingClientRect(); if (assetId) onDropAsset?.(assetId, Math.max(0, Math.min(duration, (event.clientX - rect.left) / rect.width * duration))); }}>{layers.map(layer => <button key={layer.id} className={`timeline-layer ${selected === layer.id ? "selected" : ""}`} style={{ left: `${layer.start / duration * 100}%`, width: `${Math.max(4, (layer.end - layer.start) / duration * 100)}%` }} onPointerDown={event => { event.stopPropagation(); drag.current = { id: layer.id, kind: "move", x: event.clientX, start: layer.start, end: layer.end }; event.currentTarget.setPointerCapture(event.pointerId); onSelect(layer.id); }} onPointerMove={updateAt} onPointerUp={() => { drag.current = undefined; }}><span>{layer.type === "audio" ? "♪" : layer.type === "text" ? "T" : "▦"}</span><i onPointerDown={event => { event.stopPropagation(); drag.current = { id: layer.id, kind: "resize", x: event.clientX, start: layer.start, end: layer.end }; (event.currentTarget.parentElement as HTMLButtonElement).setPointerCapture(event.pointerId); }}/></button>)}</div></div>; }
function PreviewLayer({ layer, asset, currentTime, selected, onSelect, onChange }: { layer: VisualLayer; asset?: Asset; currentTime: number; selected: boolean; onSelect: () => void; onChange: (patch: Partial<VisualLayer>) => void }) { const videoRef = useRef<HTMLVideoElement>(null); const drag = useRef<{ kind: "move" | "resize"; x: number; y: number; layer: VisualLayer } | undefined>(undefined); useEffect(() => { const video = videoRef.current; const sourceOffset = layer.type === "video" ? layer.sourceOffset ?? 0 : 0; if (video && Math.abs(video.currentTime - (currentTime - layer.start + sourceOffset)) > .12) video.currentTime = Math.max(0, currentTime - layer.start + sourceOffset); }, [currentTime, layer]); if (!asset || currentTime < layer.start || currentTime > layer.end) return null; const style = { left: `${layer.x * 100}%`, top: `${layer.y * 100}%`, width: `${layer.scale * 100}%` }; const move = (event: React.PointerEvent<HTMLButtonElement>) => { const active = drag.current; if (!active) return; const rect = event.currentTarget.parentElement!.getBoundingClientRect(); const dx = (event.clientX - active.x) / rect.width; const dy = (event.clientY - active.y) / rect.height; if (active.kind === "resize") onChange({ scale: Math.max(.01, active.layer.scale + dx) }); else onChange({ x: Math.max(0, Math.min(1, active.layer.x + dx)), y: Math.max(0, Math.min(1, active.layer.y + dy)) }); }; return <button className={`preview-layer ${selected ? "selected" : ""}`} style={style} onPointerDown={event => { drag.current = { kind: (event.target as Element).closest(".preview-resize") ? "resize" : "move", x: event.clientX, y: event.clientY, layer }; event.currentTarget.setPointerCapture(event.pointerId); onSelect(); }} onPointerMove={move} onPointerUp={() => { drag.current = undefined; }}>{layer.type === "image" ? <img src={api.fileUrl(asset.path)} alt=""/> : <video ref={videoRef} src={api.fileUrl(asset.path)} muted playsInline autoPlay loop/>}{selected && <span className="preview-resize"/>}</button>; }
function TextPreview({ layer, currentTime, selected, onSelect, onChange }: { layer: TextLayer; currentTime: number; selected: boolean; onSelect: () => void; onChange: (patch: Partial<TextLayer>) => void }) { const start = useRef<{ x: number; y: number; layer: TextLayer } | undefined>(undefined); if (currentTime < layer.start || currentTime > layer.end) return null; return <button className={`preview-text preview-text-object ${selected ? "selected" : ""}`} style={{ color: layer.color, fontFamily: layer.fontFamily ?? "Arial", fontSize: Math.max(14, layer.size / 3), textDecoration: layer.underline ? "underline" : "none", background: layer.background ? layer.backgroundColor ?? "#000000" : "transparent", borderRadius: layer.background ? layer.backgroundRadius ?? 8 : 0, left: `${layer.x * 100}%`, top: `${layer.y * 100}%` }} onPointerDown={event => { start.current = { x: event.clientX, y: event.clientY, layer }; event.currentTarget.setPointerCapture(event.pointerId); onSelect(); }} onPointerMove={event => { const active = start.current; if (!active) return; const rect = event.currentTarget.parentElement!.getBoundingClientRect(); onChange({ x: Math.max(0, Math.min(1, active.layer.x + (event.clientX - active.x) / rect.width)), y: Math.max(0, Math.min(1, active.layer.y + (event.clientY - active.y) / rect.height)) }); }} onPointerUp={() => { start.current = undefined; }}>{layer.text}</button>; }
function AudioPreview({ layer, asset, currentTime, playing }: { layer: Extract<Overlay, { type: "audio" }>; asset?: Asset; currentTime: number; playing: boolean }) { const ref = useRef<HTMLAudioElement>(null); useEffect(() => { const audio = ref.current; if (!audio) return; const active = currentTime >= layer.start && currentTime <= layer.end; const offset = Math.max(0, currentTime - layer.start); if (active && Math.abs(audio.currentTime - offset) > .18) audio.currentTime = offset; audio.volume = layer.volume; if (active && playing) void audio.play().catch(() => undefined); else audio.pause(); }, [currentTime, layer.end, layer.start, layer.volume, playing]); return asset ? <audio ref={ref} src={api.fileUrl(asset.path)}/> : null; }
function VisualControls({ layer, onChange }: { layer: VisualLayer; onChange: (patch: Partial<Overlay>) => void }) { return <div className="visual-controls"><Control label={`Розмір · ${Math.round(layer.scale * 100)}%`}><input type="number" min=".01" step=".01" value={layer.scale} onChange={event => onChange({ scale: Math.max(.01, +event.target.value || .01) })}/></Control><Control label="Горизонталь"><input type="range" min="0" max="1" step=".01" value={layer.x} onChange={event => onChange({ x: +event.target.value })}/></Control><Control label="Вертикаль"><input type="range" min="0" max="1" step=".01" value={layer.y} onChange={event => onChange({ y: +event.target.value })}/></Control></div>; }
function AssetPicker({ assets, onSelect, onImport, onClose }: { assets: Asset[]; onSelect: (asset: Asset) => void; onImport: () => void; onClose: () => void }) { return <div className="asset-picker-backdrop"><section className="asset-picker"><header><strong>Додати ресурс</strong><button className="icon-button" onClick={onClose}><X size={18}/></button></header><button className="secondary" onClick={onImport}><Plus size={16}/>Імпортувати новий файл</button><div className="picker-assets">{assets.map(asset => <button key={asset.id} onClick={() => onSelect(asset)}><span>{asset.kind === "audio" ? <Volume2 size={17}/> : asset.kind === "image" ? <ImageIcon size={17}/> : <Film size={17}/>}</span><div><strong>{asset.name}</strong><small>{asset.kind}</small></div></button>)}{!assets.length && <p>Медіатека порожня — імпортуйте файл.</p>}</div></section></div>; }
function freshEdit(clip: CandidateClip): EditDecisionList { return { projectId: clip.projectId, candidateId: clip.id, trimStart: clip.startSeconds, trimEnd: clip.endSeconds, removedRanges: [], crop: { mode: "center", zoom: 1, centerX: .5, centerY: .5 }, overlays: [], revision: 1, cutPoints: [], trackVisibility: { video: true, overlays: true, text: true, audio: true } }; }
function Control({ label, children }: { label: string; children: React.ReactNode }) { return <label className="control"><span>{label}</span>{children}</label>; }
function ShortcutsPanel() { const keys = [["Space", "Відтворити / пауза"], ["Ctrl + B", "Розрізати в курсорі"], ["Delete", "Видалити вибране"], ["Ctrl + Z", "Скасувати"], ["Ctrl + Shift + Z", "Повторити"], ["Ctrl + C / V", "Копіювати / вставити"], ["← / →", "Перейти на 5 секунд"], ["Ctrl + колесо", "Масштаб таймлайна"]]; return <><div className="inspector-title"><div><Clipboard size={18}/>Гарячі клавіші</div></div><div className="shortcuts-list">{keys.map(([key, description]) => <div key={key}><kbd>{key}</kbd><span>{description}</span></div>)}</div></>; }
